//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTheFuture
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPeople
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPeople()
        {
            this.NewPeople1 = new HashSet<NewPeople>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Sex { get; set; }
        public byte Strength { get; set; }
        public byte Perception { get; set; }
        public byte Endurance { get; set; }
        public byte Charisma { get; set; }
        public byte Intelligence { get; set; }
        public byte Agility { get; set; }
        public byte Luck { get; set; }
        public string Job { get; set; }
        public Nullable<System.Guid> Partner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPeople> NewPeople1 { get; set; }
        public virtual NewPeople NewPeople2 { get; set; }
    }
}
